apiVersion: v1
baseDomain: openshift.training
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  creationTimestamp: null
  name: upi
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.0.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    cluster: vSAN Cluster
    datacenter: vSAN Datacenter
    defaultDatastore: vsanDatastore
    network: DSwitch-VM Network-ephemeral
    password: Pass123!
    username: administrator@openshift.training
    vCenter: vcenter.openshift.training
    folder: '/vSAN Datacenter/vm/upi'
publish: External
pullSecret: 'PULL_SECRET'
sshKey: |
  SSH_KEY
